import { type Metadata } from 'next';
import './global.css';
import { type ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
